MvcApp/Controllers/AuthenticationController.cs
using Domain.Services.Authentication;
using MvcApp.ViewModels;
using MvcApp.ViewModels.AuthenticationViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace MvcApp.Controllers
{
    public class AuthenticationController : Controller
    {
        // GET: Authentication
        IAuthenticationService _service;

        public AuthenticationController(IAuthenticationService service)
        {
            _service = service;
        }


        public ActionResult Login()
        {           
            if(HttpContext.User.Identity.IsAuthenticated)
            {
                return RedirectToAction("MainPage", "Home");
            }
            return View(); 
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = _service.Login(model.Email, model.Password, model.RememberLogin);
                if (result.IsValid)
                {
                    return RedirectToAction("MainPage", "Home");
                }
                ModelState.AddModelError(string.Empty, result.ValidationMessage);
            }
            return View(model);
        }

        public ActionResult Register()
        {
            return View(); 
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var response = _service.RegisterUser(model.Email, model.Password);
                if (response.IsValid)
                {
                    _service.Login(model.Email, model.Password, false);
                    return RedirectToAction("MainPage", "Home");
                }
                else
                {
                    ModelState.AddModelError("RegisterError", response.ValidationMessage);
                    return View(model);
                }
               
            }
            return View(model);
           
        }


        
        public ActionResult ConfirmAccount(Guid userId, Guid confirmationToken)
        {
            
            var result = _service.ConfirmUser(userId, confirmationToken, true) ;
         
                if (result.IsValid)
                {
                    ViewBag.message = "Ditt konto är nu bekräftat!";
                }
                else
                {
                    ViewBag.message = result.ValidationMessage;
                }
              
                        
            return View();
            
        }

        public ActionResult Logout()
        {
            _service.Logout();
            return RedirectToAction("Login");
        }

        public ActionResult ResetPassword(Guid userId, Guid pwrToken)
        {
            if(User.Identity.IsAuthenticated)
            {
                _service.Logout();
            }            
            var result = _service.ValidatePwResetUrl(userId, pwrToken);

            if (result.IsValid)
            {
                return View();
            }
            else
            {
                ViewBag.message = result.ValidationMessage;
            }
            return View();

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ResetPassword(Guid userId, Guid pwrToken, ResetPasswordViewModel model)
        {

            if (ModelState.IsValid)
            {
                var result = _service.ResetPassword(userId, pwrToken, model.Password);
                if (result.IsValid)
                {
                    ViewBag.message = "Ditt lösenord har ändrats. Du kan nu logga in med ditt nya lösenord!";
                }
                else
                {
                    ModelState.AddModelError("PwResetError", result.ValidationMessage);
                    return View(model);
                }
            }
            return View();

        }

        [HttpGet]
        public ActionResult SendPwReset()
        {
            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SendPwReset(SendPwResetViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = _service.SendPasswordResetEmail(model.Email);
                if (result.IsValid)
                {
                    ViewBag.message = "Ett mail för lösenordsåterställning har skickats till din e-postadress!";
                    return PartialView();
                }
                else
                {
                    ModelState.AddModelError("ResetPwError", result.ValidationMessage);
                }
            }
            return PartialView(model);
        }
    }
}

MvcApp/Controllers/SettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApp.ViewModels.SettingsViewModels;

namespace MvcApp.Controllers
{
    public class SettingsController : Controller
    {
        // GET: Settings
        public ActionResult AccountSettings()
        {
            return PartialView();
        }

        public ActionResult AssociationSettings(string id)
        {
            AssociationSettingsViewModel model = new AssociationSettingsViewModel();
            model.Id = id;
            return PartialView(model);
        }

        public ActionResult EventSettings(string id)
        {
            EventSettingsViewModel model = new EventSettingsViewModel();
            model.Id = id;
            return PartialView(model);
        }
    }
}

MvcApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Swecruiser</title>
    <link href="~/Content/bootstrap-datetimepicker.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css"/>
    <link href="~/Css/Objects.css" rel="stylesheet" type="text/css"/>
    <link href="~/Css/Utility.css" rel="stylesheet" type="text/css"/>
    <link href="~/Css/Colors-Backgrounds.css" rel="stylesheet" type="text/css"/>
    <link href="~/Content/bootstrap.css" rel="stylesheet"/>
    <script src="~/Scripts/moment.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/_ajax-functions.js"></script>
    <script src="~/Scripts/_search-field.js"></script>
    <script src="~/Scripts/_visibility-toggle.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
</head>
<body>
<div class="body-alpha">
    <div class="navbar delta-background">
        <div class="col-sm-12">
            <div class="row">
                <div class="navbar-header col-sm-2">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.RouteLink("Swecruiser", "Root", null, new {@class = "logo push-left-hard heading-color"})
                </div>

                <div class="navbar-collapse collapse row ">
                    @*<div class="navbar-right col-md-4 col-sm-4 col-xs-5 ">
                  
                    </div>*@
                    @*<ul class="nav-list navbar-left nav navbar-nav ">
                        

                        <li>

                        </li>
                    </ul>*@
                    <ul class="nav-list navbar-right nav navbar-nav push-right-hard ">
                        <li>
                            <div class="nav-field text-center">
                                @Html.TextBox("Sök", null, new { @class = "js-search-field sc-input-field alpha-background ", @data_action = "../Search/SearchResultsDialogue", @data_target = "gsContainer" })
                                <div class="search-container js-clickout-hide" id="gsContainer">
                                </div>
                            </div>

                        </li>
                        <li>
                            @Html.RouteLink("Sällskap & Organisationer", "AssocMgmRoute")
                        </li>
                        <li>
                            @Html.RouteLink("Evenemang", "EventMgmRoute")
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li>
                                @Html.RouteLink("Profil", "ProfileRoute")
                            </li>
                            <li>
                                <div class="text-right " id="notificationsContainer">
                                    @{
                                        Html.RenderAction("NotificationsContainer", "Home");
                                    }
                                </div>
                            </li>
                            <li>
                                <a href="#" class="js-toggle-module pad-all-mini push-right-hard" data-container="settingsContainer">
                                    <img class="nav-img push-left-hard" src="../../Images/settings.png"/>
                                </a>
                                @{Html.RenderAction("AccountSettings", "Settings");}
                            </li>
                        }
                        else
                        {
                            <li>
                                @Html.ActionLink("Logga in", "Login", "Authentication")
                            </li>
                            <li>
                                @Html.ActionLink("Registrera", "Register", "Authentication")
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>


    <div class="container delta-background">
        @RenderBody()

    </div>
    <footer>
        <p class="heading-color">&copy; @DateTime.Now.Year - Swecruiser</p>
        <div class="modal fade sc-modal">
            <div class="modal-dialog sc-modal-container modal-sm"></div>
        </div>
    </footer>
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/bootstrap-datetimepicker.js"></script>
</body>
</html>