MvcApp/ViewModels/AssociationViewModels/AssociationInviteViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MvcApp.ViewModels.AssociationViewModels
{
    public class AssociationInviteViewModel
    {
        public AssociationInviteViewModel()
        {
            
        }
        public string id { get; set; }
        public List<InviteModel> MembersToinvite { get; set; }
    }
}

MvcApp/ViewModels/AssociationViewModels/AssociationMembershipsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Domain.Models;

namespace MvcApp.ViewModels.AssociationViewModels
{
    public class AssociationMembershipsViewModel
    {
        public ProfileInfo UserProfile { get; set; }

        public IList<MembershipViewModel> Memberships { get; set; }
    }

    public class MembershipViewModel
    {
        public AssociationRole Role { get; set; }

        public RequestResponse Response { get; set; }

        public AssociationProfileViewModel Association { get; set; }
    }
}

MvcApp/ViewModels/AssociationViewModels/AssociationProfileViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Domain.Models;

namespace MvcApp.ViewModels.AssociationViewModels
{
    public class AssociationProfileViewModel
    {
        public string Name { get; set; }

        public string id { get; set; }

        public AssociationType Type { get; set; }

        public User OwnerUser { get; set; }

        public Image BannerImage { get; set; }

        public AssociationRole ViewerRole { get; set; }

        public List<AssociationMembership> Members { get; set; }
    }
}

MvcApp/Controllers/AssociationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Helpers;
using Domain.Models;
using Domain.Services.AssociationServices;
using Domain.Services.FriendServices;
using Domain.Services.PasswordHandler;
using Domain.Services.UserServices;
using MvcApp.Filters;
using MvcApp.InfraStructure;
using MvcApp.ViewModels.AssociationViewModels;
using MvcApp.ViewModels.NotificationViewModels;
using MvcApp.ViewModels.SearchViewModels;

namespace MvcApp.Controllers
{
    public class AssociationController : Controller
    {
        private IAssociationService _service;
        private IUserService _userService;
        private IFriendService _friendService;

        public AssociationController(IAssociationService service, IUserService userService, IFriendService friendService)
        {
            _service = service;
            _userService = userService;
            _friendService = friendService;
        }

        [AuthorizePermission(Permission = "ManageAssociation")]
        public ActionResult CreateAssociation()
        {
            return PartialView();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        [AuthorizePermission(Permission = "ManageAssociation")]
        public ActionResult CreateAssociation(CreateAssociationViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = _userService.GetUserByEmail(User.Identity.Name);
                var result = _service.CreateAssociation(
                    model.Name, model.Vat, 
                    model.BannerImage,
                    user,
                    model.Category,
                    model.PrivacyType);

                if (result.IsValid)
                {
                    ViewBag.message = result.ValidationMessage;
                }
                else
                {
                    ModelState.AddModelError("creationError", result.ValidationMessage);
                }
            }
            return PartialView(model);
        }

        public ActionResult AssociationManager()
        {
            return View();
        }

        public ActionResult AssociationProfile(string name, string id)
        {
            AssociationProfileViewModel model = new AssociationProfileViewModel();
            try
            {
                User user;
                int id1 = int.Parse(Encryption.decrypt(id));
                var association = _service.GetAssociation(name, id1);
                model.Name = HttpUtility.UrlDecode(association.Name);
                model.Members = association.Members.ToList();
                model.BannerImage = association.BannerImage;
                model.Type = association.Category;
                model.OwnerUser = association.AssociationOwner;
                model.id = id;
                if (User.Identity.IsAuthenticated)
                {
                    user = _userService.GetUserByEmail(User.Identity.Name);
                    var currentMember = user != null ? association.Members.FirstOrDefault(x => x.UserId == user.UserId) : null;
                    model.ViewerRole = currentMember?.Role ?? AssociationRole.NoMember;
                }
                else
                {
                    model.ViewerRole = AssociationRole.NoMember;
                }
                
            }
            catch (Exception)
            {
                ModelState.AddModelError("Error", "Ett fel uppstod när sidan skulle laddas");
            }
            return View(model);
        }

        public ActionResult AssociationSearch(string queryString)
        {
            AssociationSearchResultViewModel model = new AssociationSearchResultViewModel();
            try
            {
                model.Results = _service.FindAssociations(queryString);
            }
            catch (Exception)
            {
               ModelState.AddModelError("Error", "Något gick fel vid sökningen");
            }
            return PartialView(model);
        }

        public ActionResult AssociationInvite(string id)
        {
            AssociationInviteViewModel model = new AssociationInviteViewModel { MembersToinvite = new List<InviteModel>()};
            try
            {
                model.id = id;
                var friends = _friendService.GetFriendsForUser(User.Identity.Name);
                if (friends != null)
                {
                    friends = _service.CheckUsersAreMembers(friends, int.Parse(Encryption.decrypt(id)));
                    if (friends != null && friends.Count > 0)
                    {
                        foreach (var friend in friends)
                        {
                            InviteModel m2 = new InviteModel();
                            m2.MemberToInvite = friend;
                            m2.Member = friend.UserId;
                            model.MembersToinvite.Add(m2);
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("NoEligible", "Du har inga vänner som inte redan är med i gruppen att bjuda in");
                    }
                    
                }
                else
                {
                    ModelState.AddModelError("NoFriends", "Du har inga vänner att bjuda in.");
                }
                
            }
            catch (Exception)
            {
                throw;
            }
            return PartialView(model);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        [AuthorizePermission(Permission = "ManageAssociation")]
        public ActionResult AssociationInvite(AssociationInviteViewModel model)
        {
            if (model.MembersToinvite != null && model.MembersToinvite.Count > 0)
            {
                var users = model.MembersToinvite.Where(x => x.IsInvited).Select(x => x.Member).ToList();
                var result = _service.InviteSelection(users, int.Parse(Encryption.decrypt(model.id)));
                if (result.IsValid)
                {
                    ViewBag.message = "Inbjudningar skickade!";
                }
            }
            else
            {
                ModelState.AddModelError("NoInvites", "Du måste välja minst en vän att bjuda in.");
            }
            return AssociationInvite(model.id);
        }

        [Authorize]
        public ActionResult AssociationMemberships()
        {
            AssociationMembershipsViewModel model = new AssociationMembershipsViewModel();
            model.Memberships = new List<MembershipViewModel>();
            List<AssociationMembership> memberships = _service.GetAssociationsForUser(User.Identity.Name);
            foreach (var membership in memberships)
            {
              model.Memberships.Add(new MembershipViewModel
              {
                 Response = membership.InviteResponse,
                 Role = membership.Role,
                 Association = new AssociationProfileViewModel
                 {
                     Name = membership.Association.Name,
                     Type = membership.Association.Category,
                     id = Encryption.encrypt(membership.Association.AssocId.ToString())
                 }
              });
            }
            return PartialView(model);
        }

        public ActionResult AssociationInviteRespondView(AssociationInviteRespondViewModel model)
        {
            return PartialView(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult AcceptAssociationInvitation(AssociationInviteRespondViewModel model)
        {
            AssociationMembership invite = new AssociationMembership();
            invite.AssocId = int.Parse(Encryption.decrypt(model.AssocId));
            invite.InviteResponse = RequestResponse.Accepted;
            var result = _service.RespondToInvite(invite, User.Identity.Name, model.NoId);
            if (result.IsValid)
            {
                ViewBag.message = result.ValidationMessage;
                model.IsResponded = true;
            }
            else
            {
                ModelState.AddModelError("Error", result.ValidationMessage);
            }
            return PartialView("AssociationInviteRespondView", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DenyAssociationInvitation(AssociationInviteRespondViewModel model)
        {
            AssociationMembership invite = new AssociationMembership();
            invite.AssocId = int.Parse(Encryption.decrypt(model.AssocId));
            invite.InviteResponse = RequestResponse.Denied;
            var result = _service.RespondToInvite(invite, User.Identity.Name, model.NoId);
            if (result.IsValid)
            {
                ViewBag.message = result.ValidationMessage;
                model.IsResponded = true;
            }
            else
            {
                ModelState.AddModelError("Error", result.ValidationMessage);
            }
            return PartialView("AssociationInviteRespondView", model);
        }

        public ActionResult UpdateAssociationProfileImage(string aid)
        {
            AssociationIdViewModel model = new AssociationIdViewModel();
            model.AssocId = aid;

            return PartialView(model);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult UpdateAssociationProfileImage(AssociationIdViewModel model, HttpPostedFileBase image)
        {
            try
            {
                var association = _service.GetAssociationById(int.Parse(Encryption.decrypt(model.AssocId)));

                if (image != null)
                {
                    var imageHandler = new ImageHandler();

MvcApp/Controllers/EntryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Helpers;
using Domain.Models;
using Domain.Services.EntryServices;
using MvcApp.ViewModels.AssociationViewModels;
using MvcApp.ViewModels.EntryViewModels;

namespace MvcApp.Controllers
{
    public class EntryController : Controller
    {
        private EntryService _service;

        public EntryController(EntryService service)
        {
            _service = service;
        }
        public ActionResult AddFriendEntry(Guid uid)
        {
            UserProfileEntryViewModel model = new UserProfileEntryViewModel();
            model.recieverId = uid;
            return PartialView(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult AddFriendEntry(UserProfileEntryViewModel model)
        {
            var result = _service.AddUserEntry(User.Identity.Name, model.recieverId, model.Message, model.IsPrivate);
            if (result.IsValid)
            {
                return RedirectToAction("GetProfileEntries", new { uid = model.recieverId });
            }
            else
            {
                ModelState.AddModelError("Error", result.ValidationMessage);
                return PartialView(model);
            }
        }

        public ActionResult GetProfileEntries(Guid uid)
        {
            List<UserProfileEntryViewModel> model = new List<UserProfileEntryViewModel>();
            var entries = _service.GetUserEntries(uid, User.Identity.Name, 0);
            if (entries != null)
            {
                foreach (var entry in entries)
                {
                    model.Add(new UserProfileEntryViewModel
                    {
                        DateTime = entry.PublishDate,
                        Author = entry.Author.ProfileInfo.Firstname + " " + entry.Author.ProfileInfo.Lastname,
                        Message = entry.Message,
                        IsPrivate = entry.IsPrivate
                    });
                }
            }
            return PartialView(model);
        }

        public ActionResult AddAssocEntry(string id)
        {
            AssociationEntryViewModel model = new AssociationEntryViewModel();
            model.AssocId = id;
            return PartialView(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult AddAssocEntry(AssociationEntryViewModel model)
        {
            var result = _service.AddAssociationEntry(User.Identity.Name,int.Parse(Encryption.decrypt(model.AssocId)), model.Message,
                model.AssociationRole, model.IsPrivate);
            return RedirectToAction("GetAssocEntries", new {id = model.AssocId, role = model.AssociationRole } );
        }
        public ActionResult GetAssocEntries(string id, AssociationRole role)
        {
            List<AssociationEntryViewModel> model = new List<AssociationEntryViewModel>();
            var result = _service.GetAssociationEntries(int.Parse(Encryption.decrypt(id)), role, 0);
            if (result != null)
            {
                foreach (var entry in result)
                {
                    model.Add(new AssociationEntryViewModel
                    {
                        AssociationRole = role,
                        Author = entry.Author?.ProfileInfo ?? null,
                        Message = entry.Message,
                        IsPrivate = entry.IsPrivate,
                        PublishDate = entry.PublishDate,
                    });
                }
            }
            return PartialView(model);
        }

        public ActionResult AddEventEntry(string id)
        {
            EventEntryViewModel model = new EventEntryViewModel();
            model.EventId = id;
            return PartialView(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult AddEventEntry(EventEntryViewModel model)
        {
            var result = _service.AddEventEntry(User.Identity.Name, int.Parse(Encryption.decrypt(model.EventId)), model.Message,
                model.Role, model.IsPrivate);
            return RedirectToAction("GetEventEntries", new { id = model.EventId, role = model.Role });
        }

        public ActionResult GetEventEntries(string id, EventRole role)
        {
            List<EventEntryViewModel> model = new List<EventEntryViewModel>();
            var result = _service.GetEventEntries(int.Parse(Encryption.decrypt(id)), role, 0);
            if (result != null)
            {
                foreach (var entry in result)
                {
                    model.Add(new EventEntryViewModel
                    {
                        Role = role,
                        Author = entry.Author?.ProfileInfo ?? null,
                        Message = entry.Message,
                        IsPrivate = entry.IsPrivate,
                        PublishDate = entry.PublishDate,
                    });
                }
            }
            return PartialView(model);
        }
    }
}

MvcApp/Controllers/SettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApp.ViewModels.SettingsViewModels;

namespace MvcApp.Controllers
{
    public class SettingsController : Controller
    {
        // GET: Settings
        public ActionResult AccountSettings()
        {
            return PartialView();
        }

        public ActionResult AssociationSettings(string id)
        {
            AssociationSettingsViewModel model = new AssociationSettingsViewModel();
            model.Id = id;
            return PartialView(model);
        }

        public ActionResult EventSettings(string id)
        {
            EventSettingsViewModel model = new EventSettingsViewModel();
            model.Id = id;
            return PartialView(model);
        }
    }
}

MvcApp/Views/Association/AssociationInvite.cshtml
@model MvcApp.ViewModels.AssociationViewModels.AssociationInviteViewModel

<div id="inviteToAssocForm" class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3>Bjud in vänner</h3>
    </div>
    @using (Ajax.BeginForm("AssociationInvite", "Association",
                                            new AjaxOptions
                                            {
                                                HttpMethod = "POST",
                                                InsertionMode = InsertionMode.Replace,
                                                UpdateTargetId = "inviteToAssocForm"
                                            }))
    {
        @Html.ValidationSummary()
        @Html.AntiForgeryToken()
        @Html.HiddenFor(x => x.id)
        <div class="modal-body row">
            @if (Model.MembersToinvite != null && Model.MembersToinvite.Count > 0)
            {
                for (int i = 0; i < Model.MembersToinvite.Count ; i++)
                {
                    <div class="col-xs-6 col-md-3">
                        <p>@Model.MembersToinvite[i].MemberToInvite.Firstname @Model.MembersToinvite[i].MemberToInvite.Lastname</p>
                        @Html.CheckBoxFor(x => x.MembersToinvite[i].IsInvited)
                    </div>
                    @Html.HiddenFor(x => x.MembersToinvite[i].Member)
                }
                <input type="submit" value="Bjud in" />
            }
        </div>
    }
    @if (ViewBag.message != null && ViewBag.message != "")
    {
        <p>@ViewBag.message</p>
    }
</div>

MvcApp/Views/Association/AssociationInviteRespondView.cshtml
@model MvcApp.ViewModels.NotificationViewModels.AssociationInviteRespondViewModel

<div class="text-center">
    @Html.ValidationSummary()
    @if (ViewBag.message != null && ViewBag.message != "")
    {
        @ViewBag.message
    }
    else
    {
        <span>Du har blivit injuden till att gå med i @Model.Name</span>
    }

</div>
@if (!Model.IsResponded)
{
    <div class="row">
        @using (Ajax.BeginForm("AcceptAssociationInvitation", "Association", FormMethod.Post,
            new AjaxOptions
            {
                HttpMethod = "POST",
                UpdateTargetId = "asContainer" + @Model.containerId
            }))
        {
            <div class="col-sm-6">
                @Html.AntiForgeryToken()
                @Html.HiddenFor(x => x.AssocId)
                @Html.HiddenFor(x => x.NoId)
                <input type="submit" value="Gå med!"/>
            </div>
        }

        @using (Ajax.BeginForm("DenyAssociationInvitation", "Association", FormMethod.Post,
            new AjaxOptions
            {
                HttpMethod = "POST",
                UpdateTargetId = "asContainer" + @Model.containerId
            }))
        {
            <div class="col-sm-6 text-right">
                @Html.AntiForgeryToken()
                @Html.HiddenFor(x => x.AssocId)
                @Html.HiddenFor(x => x.NoId)
                <input type="submit" value="Ej intresserad"/>
            </div>
        }
    </div>
}

MvcApp/Views/Association/AssociationManager.cshtml
    
<div class="row">
    <div class="col-md-12 push-bottom-soft pad-all-soft">
        <div class="center-content text-center">
            <h3 class="heading-color">Sök efter organisation eller sällskap</h3>
            @Html.TextBox("Sök", null, new {@class = "js-search-field sc-input-field alpha-background", @data_action = "/Association/AssociationSearch", @data_target = "asContainer"})
            <div class="search-container text-left overlay-dialogue center-content js-clickout-hide" id="asContainer">
            </div>
        </div>
    </div>
    <br/>
   <hr/>
    <div class="row pad-all-soft">
        <div class="col-md-6">
           
            @if (User.Identity.IsAuthenticated)
            {

                <div class="alpha-background o-module-box push-top-soft" data-action="/Association/AssociationMemberships">
                    <div class="col-sm-12 beta-background push-bottom-soft">
                        <h3>Medlemsskap</h3>
                    </div>
                    @Html.Action("AssociationMemberships")
                </div>
            }

        </div>
        <div class="col-md-6">
            @if (User.Identity.IsAuthenticated)
            {

                <div class="js-module-hide push-top-soft o-module-box alpha-background" id="createAssocContainer" data-action="/Association/CreateAssociation">
                    <div class="col-sm-12 beta-background push-bottom-soft">
                        <h3>Skapa organisation</h3>
                    </div>
                    <div id="asCrContainer">
                        @Html.Partial("CreateAssociation")
                    </div>
                    
                </div>
            }
            
        </div>
    </div>

</div>

MvcApp/Views/Association/AssociationMemberships.cshtml
@using Domain.Models
@using Microsoft.Web.Infrastructure
@using MvcApp.InfraStructure
@model MvcApp.ViewModels.AssociationViewModels.AssociationMembershipsViewModel


@if (Model != null && Model.Memberships.Any())
{
    <ul class="no-style-list ">
        @for (int i = 0; i < Model.Memberships.Count(); i++)
        {
            <li>
                <span>@Html.AssocProfileLink(Model.Memberships[i].Association.Name, Model.Memberships[i].Association.Name, Model.Memberships[i].Association.id, null)</span>
                @{

                }
                @Html.EnumLabelFor(Model.Memberships[i].Role, null)
            </li>
        }
    </ul>
    <div class="text-right pad-all-soft">
        <input class="js-toggle-module push-top-soft" type="button" value="Skapa ny organisation" data-container="createAssocContainer"/>
    </div>

}

MvcApp/Views/Association/AssociationProfile.cshtml
@using Domain.Models
@model MvcApp.ViewModels.AssociationViewModels.AssociationProfileViewModel
@{
    ViewBag.Title = @Model.Name;
}

<div class="row">
    <div class="col-sm-8">
        <h2 class="heading-color">@Model.Name</h2>
    </div>
    <div class="col-sm-4 text-right pad-all-soft">
        <a href="#" class="js-toggle-module pad-all-mini push-right-hard" data-container="assocSettingsContainer">
            <img class="nav-img push-left-hard" src="../../Images/settings.png"/>
        </a>
            @Html.Action("AssociationSettings", "Settings", new { id = Model.id })
    </div>

</div>
<div class="push-bottom-soft col-xs-12">
    <div class="alpha-background push-bottom-soft text-right">
        @if (Model.BannerImage != null)
        {
            <img class="image-control" src="@Model.BannerImage.Path" />
        }
        else
        {
            <img class="image-control" src="~/Images/Svg/../carsilhouette.png" />
        }
    </div>
</div>


<div class="col-sm-6 alpha-background o-module-box pad-bottom-hard no-pad-sides push-bottom-soft">
    <div class="beta-background col-xs-12">
        <h3 class="text-color-dark">Medlemmar</h3>
    </div>

    @foreach (var member in @Model.Members.Where(x => x.InviteResponse == RequestResponse.Accepted))
    {
        <div class="col-xs-4 no-pad">
            <div class="pad-all-hard">
                <a href="/Profile?uid=@member.UserId" class="no-style-link">
                    <div class="text-center no-pad">

                        @if (member.User.ProfileImage != null)
                        {
                            <img class="image-control" src="@Url.Content(member.User.ProfileImage.Path)" width="100" height="100" />
                        }
                        else
                        {
                            <img class="image-control" src="~/Images/Svg/Avatar.svg" width="100" height="100" />
                        }
                        <div class="col-xs-12 alpha ">
                            @member.User.Firstname @member.User.Lastname
                        </div>

                    </div>
                </a>
            </div>

        </div>
    }
</div>
<div class="col-sm-6">
    <div class="alpha-background no-pad-sides ">
        <div class="col-sm-12 beta-background">
            <h3>Meddelanden</h3>
        </div>
        <div id="assocEntriesContainer" class="pad-all-hard alpha-background col-sm-12 push-bottom-soft">
            @Html.Action("GetAssocEntries", "Entry", new {id = Model.id, role = Model.ViewerRole})
        </div>
    </div>
        @if (Model.ViewerRole != AssociationRole.NoMember)
        {
            <div class="col-sm-12 alpha-background pad-all-hard push-bottom-soft">
                @Html.Action("AddAssocEntry", "Entry", new { id = Model.id })
            </div>
        }
</div>

MvcApp/Views/Association/AssociationSearch.cshtml
@model MvcApp.ViewModels.SearchViewModels.AssociationSearchResultViewModel


<div class="o-module-box alpha-background">
    @if (Model.Results != null && Model.Results.Count > 0)
    {
        <ul class="search-list no-style-list no-pad no-gutter-all">
            @foreach (var profile in Model.Results)
            {

            <li>
                <a href="@profile.Link">
                    <div class="col-sm-2">

                    </div>
                    <div class="col-sm-6">
                        @profile.Name
                    </div>
                    <div class="col-sm-4">
                        @Html.Label(profile.AssociationType.ToString())
                    </div>
                </a>
                </li>
            }
        </ul>
    }
    else
    {
        <div class="pad-all-soft">
            <p>Inga sökresultat hittades.</p>
        </div>
    }
</div>

MvcApp/Views/Association/CreateAssociation.cshtml
@model MvcApp.ViewModels.AssociationViewModels.CreateAssociationViewModel

<div id="creationContainer">
    @using (Ajax.BeginForm("CreateAssociation", "Association", FormMethod.Post, new AjaxOptions
    {
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "asCrContainer"

    }))
    {
        @Html.ValidationSummary()
        @Html.AntiForgeryToken()
        <div class="modal-body">
            <ul class="no-style-list">
                <li>
                    @Html.LabelFor(x => x.Name)
                </li>
                <li>
                    @Html.TextBoxFor(x => x.Name)
                </li>
                <li>
                    @Html.LabelFor(x => x.Category)
                </li>
                <li>
                    @Html.EnumDropDownListFor(x => x.Category)
                </li>
                <li>
                    @Html.LabelFor(x => x.PrivacyType)
                </li>
                <li>
                    @Html.EnumDropDownListFor(x => x.PrivacyType)
                </li>
                <li>
                    @Html.LabelFor(x => x.BannerImage)
                </li>
                <li>
                    <input type="submit" class="btn btn-default" value="Spara ändringar" />
                </li>
                @if (ViewBag.message != null)
                {
                    <li>
                        @ViewBag.message
                    </li>
                }

            </ul>
        </div>
    }

</div>

MvcApp/Views/Association/UpdateAssociationProfileImage.cshtml
@model MvcApp.ViewModels.AssociationViewModels.AssociationIdViewModel
<div id="updateAssocProfileImageForm" class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3>Ändra dina uppgifter</h3>
    </div>
    @using (Html.BeginForm("UpdateAssociationProfileImage", "Association", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.ValidationSummary()
        @Html.AntiForgeryToken()
        <div class="modal-body">
            <ul class="no-style-list">
                <li>
                    <label for="image">Lägg upp ny bild</label>
                </li>
                <li>
                    <input type="file" name="image" id="image" style="width: 100%;" />
                </li>
                <li>
                    <input type="submit" class="btn btn-default" value="Spara"/>
                </li>
                @if (ViewBag.message != null)
                {
                    <li>
                        @ViewBag.message
                    </li>
                }
                @Html.HiddenFor(x => x.AssocId)
            </ul>
        </div>
    }
</div>