MvcApp/ViewModels/EventViewModels/CreateEventViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Domain.Models;

namespace MvcApp.ViewModels.EventViewModels
{
    public class CreateEventViewModel
    {
        public string Name { get; set; }

        public string Description { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime StartDate { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime EndDate { get; set; }

        public EventType Category { get; set; }
    }
}

MvcApp/ViewModels/EventViewModels/EventInviteViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MvcApp.ViewModels.AssociationViewModels;

namespace MvcApp.ViewModels.EventViewModels
{
    public class EventInviteViewModel
    {
        public string EventId { get; set; }
        public List<InviteModel> ParticipantsToinvite { get; set; }
    }
    
}

MvcApp/ViewModels/EventViewModels/EventParticipationsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Domain.Models;

namespace MvcApp.ViewModels.EventViewModels
{
    public class EventParticipationsViewModel
    {
     
            public ProfileInfo UserProfile { get; set; }

            public IList<ParticipantViewModel> Participants { get; set; }
     
    }
    public class ParticipantViewModel
    {
        public EventRole Role { get; set; }

        public Rsvp Response { get; set; }

        public EventProfileViewModel Event { get; set; }
    }
}

MvcApp/Controllers/EntryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Helpers;
using Domain.Models;
using Domain.Services.EntryServices;
using MvcApp.ViewModels.AssociationViewModels;
using MvcApp.ViewModels.EntryViewModels;

namespace MvcApp.Controllers
{
    public class EntryController : Controller
    {
        private EntryService _service;

        public EntryController(EntryService service)
        {
            _service = service;
        }
        public ActionResult AddFriendEntry(Guid uid)
        {
            UserProfileEntryViewModel model = new UserProfileEntryViewModel();
            model.recieverId = uid;
            return PartialView(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult AddFriendEntry(UserProfileEntryViewModel model)
        {
            var result = _service.AddUserEntry(User.Identity.Name, model.recieverId, model.Message, model.IsPrivate);
            if (result.IsValid)
            {
                return RedirectToAction("GetProfileEntries", new { uid = model.recieverId });
            }
            else
            {
                ModelState.AddModelError("Error", result.ValidationMessage);
                return PartialView(model);
            }
        }

        public ActionResult GetProfileEntries(Guid uid)
        {
            List<UserProfileEntryViewModel> model = new List<UserProfileEntryViewModel>();
            var entries = _service.GetUserEntries(uid, User.Identity.Name, 0);
            if (entries != null)
            {
                foreach (var entry in entries)
                {
                    model.Add(new UserProfileEntryViewModel
                    {
                        DateTime = entry.PublishDate,
                        Author = entry.Author.ProfileInfo.Firstname + " " + entry.Author.ProfileInfo.Lastname,
                        Message = entry.Message,
                        IsPrivate = entry.IsPrivate
                    });
                }
            }
            return PartialView(model);
        }

        public ActionResult AddAssocEntry(string id)
        {
            AssociationEntryViewModel model = new AssociationEntryViewModel();
            model.AssocId = id;
            return PartialView(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult AddAssocEntry(AssociationEntryViewModel model)
        {
            var result = _service.AddAssociationEntry(User.Identity.Name,int.Parse(Encryption.decrypt(model.AssocId)), model.Message,
                model.AssociationRole, model.IsPrivate);
            return RedirectToAction("GetAssocEntries", new {id = model.AssocId, role = model.AssociationRole } );
        }
        public ActionResult GetAssocEntries(string id, AssociationRole role)
        {
            List<AssociationEntryViewModel> model = new List<AssociationEntryViewModel>();
            var result = _service.GetAssociationEntries(int.Parse(Encryption.decrypt(id)), role, 0);
            if (result != null)
            {
                foreach (var entry in result)
                {
                    model.Add(new AssociationEntryViewModel
                    {
                        AssociationRole = role,
                        Author = entry.Author?.ProfileInfo ?? null,
                        Message = entry.Message,
                        IsPrivate = entry.IsPrivate,
                        PublishDate = entry.PublishDate,
                    });
                }
            }
            return PartialView(model);
        }

        public ActionResult AddEventEntry(string id)
        {
            EventEntryViewModel model = new EventEntryViewModel();
            model.EventId = id;
            return PartialView(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult AddEventEntry(EventEntryViewModel model)
        {
            var result = _service.AddEventEntry(User.Identity.Name, int.Parse(Encryption.decrypt(model.EventId)), model.Message,
                model.Role, model.IsPrivate);
            return RedirectToAction("GetEventEntries", new { id = model.EventId, role = model.Role });
        }

        public ActionResult GetEventEntries(string id, EventRole role)
        {
            List<EventEntryViewModel> model = new List<EventEntryViewModel>();
            var result = _service.GetEventEntries(int.Parse(Encryption.decrypt(id)), role, 0);
            if (result != null)
            {
                foreach (var entry in result)
                {
                    model.Add(new EventEntryViewModel
                    {
                        Role = role,
                        Author = entry.Author?.ProfileInfo ?? null,
                        Message = entry.Message,
                        IsPrivate = entry.IsPrivate,
                        PublishDate = entry.PublishDate,
                    });
                }
            }
            return PartialView(model);
        }
    }
}

MvcApp/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Helpers;
using Domain.Models;
using Domain.Services.EventServices;
using Domain.Services.UserServices;
using MvcApp.Filters;
using MvcApp.InfraStructure;
using MvcApp.ViewModels.AssociationViewModels;
using MvcApp.ViewModels.EventViewModels;
using MvcApp.ViewModels.NotificationViewModels;
using MvcApp.ViewModels.SearchViewModels;

namespace MvcApp.Controllers
{
    public class EventController : Controller
    {

        private IEventService _service;
        private IUserService _userService;

        public EventController(IEventService service, IUserService userService)
        {
            _service = service;
            _userService = userService;
        }

        
        // GET: Event
        //public ActionResult ()
        //{
        //    return View();
        //}
        [AllowAnonymous]
        public ActionResult EventManager()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult EventProfile(string id)
        {
            try
            {
                User user;
                var theEvent = _service.GetEventById(int.Parse(Encryption.decrypt(id)));
                EventProfileViewModel model = new EventProfileViewModel
                {
                    Name = theEvent.Name,
                    BannerImage = theEvent.BannerImage,
                    EventId = Encryption.encrypt(theEvent.Id.ToString()),
                    Description = theEvent.Description,
                    Participants = theEvent.Invites.ToList(),
                    EndDate = theEvent.EndTime,
                    StartDate = theEvent.StartTime
      
                };
                if (User.Identity.IsAuthenticated)
                {
                    user = _userService.GetUserByEmail(User.Identity.Name);
                    var currentMember = user != null ? theEvent.Invites.FirstOrDefault(x => x.UserId == user.UserId) : null;
                    model.ViewerRole = currentMember?.Role ?? EventRole.NotAccepted;
                }
                else
                {
                    model.ViewerRole = EventRole.NotAccepted;
                }
                return View(model);
            }
            catch (Exception)
            {
                throw;
            }
        }

        [AuthorizePermission( Permission = "ManageEvent")]
        public ActionResult CreateEvent()
        {
            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizePermission(Permission = "ManageEvent")]
        public ActionResult CreateEvent(CreateEventViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = _service.CreateEvent(model.Description, model.Name, model.StartDate, model.EndDate,
                model.Category, User.Identity.Name);
                if (result.IsValid)
                {
                    ViewBag.message = result.ValidationMessage;
                }
                else
                {
                    ModelState.AddModelError("Error", result.ValidationMessage);
                }
            }

            return PartialView(model);
        }
        

        [AuthorizePermission(Permission = "ManageEvent")]
        public ActionResult SendInvitations()
        {
            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizePermission(Permission = "ManageEvent")]
        public ActionResult SendInvitations(EventInviteViewModel model)
        {
            return PartialView(model);
        }

        public ActionResult EventSearch(string queryString)
        {
            EventSearchViewModel model = new EventSearchViewModel();
            try
            {
                model.Results = _service.GetEvents(queryString);
            }
            catch (Exception)
            {
                ModelState.AddModelError("Error", "Något gick fel vid sökningen");
            }
            return PartialView(model);
        }

        [Authorize]
        public ActionResult EventParticipations()
        {
            EventParticipationsViewModel model = new EventParticipationsViewModel();
            model.Participants = new List<ParticipantViewModel>();
            List<EventParticipation> participations = _service.GetEventsForUser(User.Identity.Name);
            foreach (var participation in participations)
            {
                model.Participants.Add(new ParticipantViewModel
                {
                    Response = participation.Rsvp,
                    Role = participation.Role,
                    Event = new EventProfileViewModel
                    {
                        Name = participation.Event.Name,
                        Category = participation.Event.Category,
                        EventId = Encryption.encrypt(participation.Event.Id.ToString())
                    }
                });
            }
            return PartialView(model);
        }

        public ActionResult EventInvite(string id)
        {
            EventInviteViewModel model = new EventInviteViewModel { ParticipantsToinvite = new List<InviteModel>() };
            try
            {
                model.EventId = id;
               
                    var friends = _service.GetFriendsViableForInvite(User.Identity.Name, int.Parse(Encryption.decrypt(id)));
                    if (friends != null && friends.Count > 0)
                    {
                        foreach (var friend in friends)
                        {
                            InviteModel m2 = new InviteModel();
                            m2.MemberToInvite = friend;
                            m2.Member = friend.UserId;
                            model.ParticipantsToinvite.Add(m2);
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("NoEligible", "Du har inga vänner som inte redan är inbjudna att bjuda in");
                    }

            }
            catch (Exception)
            {
                throw;
            }
            return PartialView(model);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        [AuthorizePermission(Permission = "ManageAssociation")]
        public ActionResult EventInvite(EventInviteViewModel model)
        {
            if (model.ParticipantsToinvite != null && model.ParticipantsToinvite.Count > 0)
            {
                var users = model.ParticipantsToinvite.Where(x => x.IsInvited).Select(x => x.Member).ToList();
                var result = _service.InviteSelection(users, int.Parse(Encryption.decrypt(model.EventId)));
                if (result.IsValid)
                {
                    ViewBag.message = "Inbjudningar skickade!";
                }
            }
            else
            {
                ModelState.AddModelError("NoInvites", "Du måste välja minst en vän att bjuda in.");
            }
            return EventInvite(model.EventId);
        }

        public ActionResult EventInviteRespondView(EventInviteRespondViewModel model)
        {
            return PartialView(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult AcceptEventInvitation(EventInviteRespondViewModel model)
        {
            EventParticipation invite = new EventParticipation();
            invite.EventId = int.Parse(Encryption.decrypt(model.EventId));
            invite.Rsvp = Rsvp.Attending;
            var result = _service.RespondToInvite(invite, User.Identity.Name, model.NoId);
            if (result.IsValid)
            {
                ViewBag.message = result.ValidationMessage;
                model.IsResponded = true;
            }
            else
            {
                ModelState.AddModelError("Error", result.ValidationMessage);
            }
            return PartialView("EventInviteRespondView", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DenyEventInvitation(EventInviteRespondViewModel model)
        {
            EventParticipation invite = new EventParticipation();
            invite.EventId = int.Parse(Encryption.decrypt(model.EventId));
            invite.Rsvp = Rsvp.NotResponded;
            var result = _service.RespondToInvite(invite, User.Identity.Name, model.NoId);
            if (result.IsValid)
            {
                ViewBag.message = result.ValidationMessage;
                model.IsResponded = true;
            }
            else
            {
                ModelState.AddModelError("Error", result.ValidationMessage);
            }
            return PartialView("EventInviteRespondView", model);
        }
        public ActionResult UpdateEventProfileImage(string eid)
        {
            EventIdModel model = new EventIdModel();
            model.EventId = eid;

            return PartialView(model);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult UpdateEventProfileImage(EventIdModel model, HttpPostedFileBase image)
        {
            try
            {
                var theEvent = _service.GetEventById(int.Parse(Encryption.decrypt(model.EventId)));

                if (image != null)
                {
                    var imageHandler = new ImageHandler();
                    string pic = imageHandler.AddImage(Server, image, "eid=" + theEvent.Id, "Events");
                    theEvent.BannerImage = new Image { Path = "/Images/Events/" + pic };
                    _service.EditEvent(theEvent);

                }
                return RedirectToAction("EventProfile", new { name = theEvent.Name, id = model.EventId });
            }
            catch (Exception)
            {

MvcApp/Controllers/SettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApp.ViewModels.SettingsViewModels;

namespace MvcApp.Controllers
{
    public class SettingsController : Controller
    {
        // GET: Settings
        public ActionResult AccountSettings()
        {
            return PartialView();
        }

        public ActionResult AssociationSettings(string id)
        {
            AssociationSettingsViewModel model = new AssociationSettingsViewModel();
            model.Id = id;
            return PartialView(model);
        }

        public ActionResult EventSettings(string id)
        {
            EventSettingsViewModel model = new EventSettingsViewModel();
            model.Id = id;
            return PartialView(model);
        }
    }
}

MvcApp/Views/Event/CreateEvent.cshtml
@model MvcApp.ViewModels.EventViewModels.CreateEventViewModel

<div id="creationContainer">
    @using (Ajax.BeginForm("CreateEvent", "Event", FormMethod.Post, new AjaxOptions
    {
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "evCrContainer"

    }))
    {
        @Html.ValidationSummary()
        @Html.AntiForgeryToken()
        <div class="modal-body row">
            <div class="col-md-3">
                <ul class="no-style-list">
                    <li>
                        @Html.LabelFor(x => x.Name)
                    </li>
                    <li>
                        @Html.TextBoxFor(x => x.Name)
                    </li>
                    <li>
                        @Html.LabelFor(x => x.Category)
                    </li>
                    <li>
                        @Html.EnumDropDownListFor(x => x.Category)
                    </li>
                    <li>
                        @Html.LabelFor(x => x.Description)
                    </li>
                    <li>
                        @Html.TextAreaFor(x => x.Description)
                    </li>
                    <li>
                        <input type="submit" class="btn btn-default" value="Spara ändringar"/>
                    </li>
                    @if (ViewBag.message != null)
                    {
                        <li>
                            @ViewBag.message
                        </li>
                    }

                </ul>
            </div>
            <div class="col-md-3">
                <ul class="no-style-list">
                    <li>
                        @Html.LabelFor(x => x.StartDate)
                    </li>
                    <li>
                        <div class='input-group date' id='startDate'>
                            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control", @name = "startDate", @data_format = "YYYY-MM-DD HH:mm" } })
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </li>
                    <li>
                        @Html.LabelFor(x => x.EndDate)
                    </li>
                    <li>
                        <div class='input-group date' id='endDate'>
                            @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control", @name = "endDate", @data_format = "YYYY-MM-DD HH:mm" } })
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </li>
                </ul>
            </div>
            </div>
    }

</div>
<script type="text/javascript">
                        $(document).ready(function() {
                            $('#startDate').datetimepicker({
                                format: 'YYYY-MM-DD HH:mm'
                            });
                            $('#endDate').datetimepicker({
                                format: 'YYYY-MM-DD HH:mm'
                            });
 
                            jQuery("#startDate").on("dp.change", function (e) {
                                $('#endDate').data("DateTimePicker").minDate(e.date);
                            });
                            jQuery("#endDate").on("dp.change", function (e) {
                                $('#startDate').data("DateTimePicker").maxDate(e.date);

                            });
                        });
                        
</script>

MvcApp/Views/Event/EventInvite.cshtml
@model MvcApp.ViewModels.EventViewModels.EventInviteViewModel

<div id="inviteToEventForm" class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3>Bjud in vänner</h3>
    </div>
    @using (Ajax.BeginForm("EventInvite", "Event",
                                                    new AjaxOptions
                                                    {
                                                        HttpMethod = "POST",
                                                        InsertionMode = InsertionMode.Replace,
                                                        UpdateTargetId = "inviteToEventForm"
                                                    }))
    {
        @Html.ValidationSummary()
        @Html.AntiForgeryToken()
        @Html.HiddenFor(x => x.EventId)
        <div class="modal-body row">
            @if (Model.ParticipantsToinvite != null && Model.ParticipantsToinvite.Count > 0)
            {
                for (int i = 0; i < Model.ParticipantsToinvite.Count; i++)
                {
                    <div class="col-xs-6 col-md-3">
                        <p>@Model.ParticipantsToinvite[i].MemberToInvite.Firstname @Model.ParticipantsToinvite[i].MemberToInvite.Lastname</p>
                        @Html.CheckBoxFor(x => x.ParticipantsToinvite[i].IsInvited)
                    </div>
                    @Html.HiddenFor(x => x.ParticipantsToinvite[i].Member)
                }
                <input type="submit" value="Bjud in" />
            }
        </div>
    }
    @if (ViewBag.message != null && ViewBag.message != "")
    {
        <p>@ViewBag.message</p>
    }
</div>

MvcApp/Views/Event/EventInviteRespondView.cshtml
@model MvcApp.ViewModels.NotificationViewModels.EventInviteRespondViewModel

<div class="text-center">
    @Html.ValidationSummary()
    @if (ViewBag.message != null && ViewBag.message != "")
    {
        @ViewBag.message
    }
    else
    {
        <span>Du har blivit injuden till @Model.Name</span>
    }

</div>
@if (!Model.IsResponded)
{
    <div class="row">
        @using (Ajax.BeginForm("AcceptEventInvitation", "Event", FormMethod.Post,
                    new AjaxOptions
                    {
                        HttpMethod = "POST",
                        UpdateTargetId = "evContainer" + @Model.containerId
                    }))
        {
            <div class="col-sm-6">
                @Html.AntiForgeryToken()
                @Html.HiddenFor(x => x.EventId)
                @Html.HiddenFor(x => x.NoId)
                <input type="submit" value="Gå med!" />
            </div>
        }

        @using (Ajax.BeginForm("DenyEventInvitation", "Event", FormMethod.Post,
                    new AjaxOptions
                    {
                        HttpMethod = "POST",
                        UpdateTargetId = "evContainer" + @Model.containerId
                    }))
        {
            <div class="col-sm-6 text-right">
                @Html.AntiForgeryToken()
                @Html.HiddenFor(x => x.EventId)
                @Html.HiddenFor(x => x.NoId)
                <input type="submit" value="Ej intresserad" />
            </div>
        }
    </div>
}

MvcApp/Views/Event/EventManager.cshtml
<div class="row">
    <div class="col-md-12 push-bottom-soft pad-all-soft">
        <div class="center-content text-center">
            <h3 class="heading-color">Sök efter evenemang</h3>
            @Html.TextBox("Sök", null, new { @class = "js-search-field sc-input-field alpha-background", @data_action = "/Event/EventSearch", @data_target = "evContainer" })
            <div class="search-container text-left overlay-dialogue center-content js-clickout-hide" id="evContainer">
            </div>
        </div>
    </div>
    <br />
    <hr />
    <div class="row pad-all-soft">
        <div class="col-md-6">

            @if (User.Identity.IsAuthenticated)
            {
                <div class="alpha-background o-module-box push-top-soft" data-action="/Association/AssociationMemberships">
                    <div class="col-sm-12 beta-background push-bottom-soft">
                        <h3>Deltagande i evenemang</h3>
                    </div>
                    @Html.Action("EventParticipations")
                </div>
            }

        </div>

    </div>
    <div class="col-md-12">
        @if (User.Identity.IsAuthenticated)
            {

            <div class="js-module-hide push-top-soft o-module-box alpha-background" id="createEventContainer" data-action="/Event/CreateEvent">
                <div class="col-sm-12 beta-background push-bottom-soft">
                    <h3>Skapa nytt evenemang</h3>
                </div>
                <div id="evCrContainer">
                    @Html.Partial("CreateEvent")
                </div>

            </div>
        }

    </div>



</div>

MvcApp/Views/Event/EventProfile.cshtml
@using Domain.Models
@model MvcApp.ViewModels.EventViewModels.EventProfileViewModel
@{
    ViewBag.Title = @Model.Name;
}

<div class="row">
    <div class="col-sm-8">
        <h2 class="heading-color">@Model.Name</h2>
    </div>
    <div class="col-sm-4 text-right pad-all-soft">
        <a href="#" class="js-toggle-module pad-all-mini push-right-hard" data-container="eventSettingsContainer">
            <img class="nav-img push-left-hard" src="../../Images/settings.png" />
        </a>
        @Html.Action("EventSettings", "Settings", new { id = Model.EventId })
    </div>

</div>
<div class="push-bottom-soft col-xs-12">
    <div class="alpha-background push-bottom-soft text-right">
        @if (Model.BannerImage != null)
        {
            <img class="image-control" src="@Model.BannerImage.Path" />
        }
        else
        {
            <img class="image-control" src="~/Images/Svg/../carsilhouette.png" />
        }
    </div>
</div>
<div class="col-sm-12 alpha-background o-module-box pad-bottom-hard no-pad-sides push-bottom-soft">
    <div class="beta-background col-xs-12">
        <h3 class="text-color-dark">Om evenemanget</h3>
    </div>
    <div class="row pad-all-soft">
        <div class="col-sm-4 pad-all-hard">
            @Html.LabelFor(x => x.Description)<br />
            @Html.DisplayFor(x => x.Description)
        </div>
        <div class="col-sm-4 pad-all-hard">
            @Html.LabelFor(x => x.StartDate)<br/>
            @Html.DisplayFor(x => x.StartDate)
        </div>
        <div class="col-sm-4 pad-all-hard">
            @Html.LabelFor(x => x.EndDate)<br />
            @Html.DisplayFor(x => x.EndDate)
        </div>
    </div>
</div>


<div class="col-sm-6 alpha-background o-module-box pad-bottom-hard no-pad-sides push-bottom-soft">
    <div class="beta-background col-xs-12">
        <h3 class="text-color-dark">Deltagare</h3>
    </div>

    @foreach (var member in @Model.Participants.Where(x => x.Rsvp == Rsvp.Attending))
    {
        <div class="col-xs-4 no-pad">
            <div class="pad-all-hard">
                <a href="/Profile?uid=@member.UserId" class="no-style-link">
                    <div class="text-center no-pad">

                        @if (member.InvitedUser.ProfileImage != null)
                        {
                            <img class="image-control" src="@Url.Content(member.InvitedUser.ProfileImage.Path)" width="100" height="100" />
                        }
                        else
                        {
                            <img class="image-control" src="~/Images/Svg/Avatar.svg" width="100" height="100" />
                        }
                        <div class="col-xs-12 alpha ">
                            @member.InvitedUser.Firstname @member.InvitedUser.Lastname
                        </div>

                    </div>
                </a>
            </div>

        </div>
    }
</div>
<div class="col-sm-6">
    <div class="alpha-background no-pad-sides ">
        <div class="col-sm-12 beta-background">
            <h3>Meddelanden</h3>
        </div>
        <div id="eventEntriesContainer" class="pad-all-hard alpha-background col-sm-12 push-bottom-soft">
            @Html.Action("GetEventEntries", "Entry", new { id = Model.EventId, role = Model.ViewerRole })
        </div>
    </div>
    @if (Model.ViewerRole != EventRole.NotInvited)
    {
        <div class="col-sm-12 alpha-background pad-all-hard push-bottom-soft">
            @Html.Action("AddEventEntry", "Entry", new { id = Model.EventId })
        </div>
    }
</div>

MvcApp/Views/Event/UpdateEventProfileImage.cshtml
@model MvcApp.ViewModels.EventViewModels.EventIdModel
<div id="updateAssocProfileImageForm" class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3>Ändra dina uppgifter</h3>
    </div>
    @using (Html.BeginForm("UpdateEventProfileImage", "Event", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.ValidationSummary()
        @Html.AntiForgeryToken()
        <div class="modal-body">
            <ul class="no-style-list">
                <li>
                    <label for="image">Lägg upp ny bild</label>
                </li>
                <li>
                    <input type="file" name="image" id="image" style="width: 100%;" />
                </li>
                <li>
                    <input type="submit" class="btn btn-default" value="Spara" />
                </li>
                @if (ViewBag.message != null)
                {
                    <li>
                        @ViewBag.message
                    </li>
                }
                @Html.HiddenFor(x => x.EventId)
            </ul>
        </div>
    }
</div>